#ifndef WW_H
#define WW_H


#define WW_WIDTH (320)
#define WW_HEIGHT (240)
#include "wwError.h"
#include "wwMacro.h"
#include "wwTimer.h"
#include "wwGray.h"
#include "wwValue.h"
#include "wwMapColor.h"
#include "wwMapValue.h"
#include "wwMapVector.h"
#include "wwMapGray.h"
#include "wwMapPointer.h"
#include "wwOperatorSimple.h"
#include "wwConvert.h"
#include "wwSplit.h"
#include "wwMerge.h"
#include "wwRemapGray.h"
#include "wwRemapGrayColor.h"
#include "wwMultiply.h"
#include "wwScale.h"
#include "wwInvert.h"
#include "wwAdd.h"
#include "wwAddClipped.h"
#include "wwOverlay.h"
#include "wwColorize.h"
#include "wwFilePPM.h"
#include "wwFileInPPM.h"
#include "wwGradientFilePPM.h"
#include "wwNoisePerlin.h"
#include "wwSlope.h"
#include "wwWarp.h"
#include "wwDisplaySDL.h"
#include "wwCameraV4L.h"
#include "wwGamma.h"
#include "wwBlurFast.h"
#include "wwBlurBox.h"
#include "wwRub.h"
#include "wwTimeBlur.h"
#include "wwLocator.h"
#include "wwMain.h"
#include "wwStretch.h"
#include "wwBurn.h"
#include "wwFireRender.h"
#include "wwWater.h"
#include "wwWaterSpigot.h"
#include "wwWaterSpigotRandom.h"
#include "wwWaterSpigotMultiRandom.h"
#include "wwWaterSimulator.h"
#include "wwWaterRender.h"
#include "wwWaterWorks.h"
#include "wwBloodRender.h"
#include "wwBloodWorks.h"
#include "wwSlimeRender.h"
#include "wwSlimeWorks.h"
#include "wwGhostWorks.h"
#include "wwFireSimulator.h"
#include "wwFireWorks.h"
#include "wwSkinny.h"
#include "wwFatty.h"
#include "wwProto.h"
#include "wwToonWorks.h"



#endif
