// error list


#define WW_QUIT 0

#define WW_ERR_SDL_GENERAL 100
#define WW_ERR_V4L_GENERAL 200
#define WW_ERR_GHOST_GENERAL 300
#define WW_ERR_FILEPPM_GENERAL 400
#define WW_ERR_GRADIENTFILEPPM_GENERAL 500
